// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ota.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	ota.proto

It has these top-level messages:
	UpdateRequest
	UpdateReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateRequest struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type UpdateReply struct {
	Ok      bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *UpdateReply) Reset()                    { *m = UpdateReply{} }
func (m *UpdateReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateReply) ProtoMessage()               {}
func (*UpdateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *UpdateReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateRequest)(nil), "service.UpdateRequest")
	proto.RegisterType((*UpdateReply)(nil), "service.UpdateReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ota service

type OtaClient interface {
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateReply, error)
}

type otaClient struct {
	cc *grpc.ClientConn
}

func NewOtaClient(cc *grpc.ClientConn) OtaClient {
	return &otaClient{cc}
}

func (c *otaClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateReply, error) {
	out := new(UpdateReply)
	err := grpc.Invoke(ctx, "/service.Ota/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ota service

type OtaServer interface {
	Update(context.Context, *UpdateRequest) (*UpdateReply, error)
}

func RegisterOtaServer(s *grpc.Server, srv OtaServer) {
	s.RegisterService(&_Ota_serviceDesc, srv)
}

func _Ota_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtaServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ota/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtaServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ota_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Ota",
	HandlerType: (*OtaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _Ota_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ota.proto",
}

func init() { proto.RegisterFile("ota.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2f, 0x49, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55, 0x52,
	0xe4, 0xe2, 0x0d, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x12, 0xe0, 0x62, 0x2e, 0x2d, 0xca, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95,
	0xcc, 0xb9, 0xb8, 0x61, 0x4a, 0x0a, 0x72, 0x2a, 0x85, 0xf8, 0xb8, 0x98, 0xf2, 0xb3, 0xc1, 0xf2,
	0x1c, 0x41, 0x4c, 0xf9, 0xd9, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9,
	0x12, 0x4c, 0x60, 0x4d, 0x30, 0xae, 0x91, 0x3d, 0x17, 0xb3, 0x7f, 0x49, 0xa2, 0x90, 0x05, 0x17,
	0x1b, 0x44, 0xbf, 0x90, 0x98, 0x1e, 0xd4, 0x5a, 0x3d, 0x14, 0x3b, 0xa5, 0x44, 0x30, 0xc4, 0x0b,
	0x72, 0x2a, 0x95, 0x18, 0x9c, 0x58, 0xa2, 0x98, 0x0a, 0x92, 0x92, 0xd8, 0xc0, 0x4e, 0x36, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xb1, 0xe3, 0x54, 0xbf, 0x00, 0x00, 0x00,
}
